---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-app-preview-environment
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - pullRequest:
      # When using a Pull Request generator, the ApplicationSet controller polls every `requeueAfterSeconds` interval (defaulting to every 30 minutes) to detect changes.
      requeueAfterSeconds: 90 # Poll every 90 seconds to detect changes.
      github:
        owner: $OWNER
        repo: $REPO
        labels:
        - preview
  template:
    metadata:
      name: todo-app-preview-{{.number}}
      labels:
        environment: preview
        app: todo-app
    spec:
      project: default
      source:
        directory:
          include: '{*.yml,*.yaml}'
        repoURL: https://github.com/$OWNER/$REPO.git
        targetRevision: preview-{{.number}}
        path: .
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: true
