---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
    - image: rminz/todo-app # TODO: Replace it with your own image registry
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: "{{.TIER}}"
        chartPath: kubernetes/charts/todo-app
        valuesFiles:
          - kubernetes/deployment-values/{{.TIER}}/values.yaml
        setValueTemplates:
          tier: "{{.TIER}}"
          version: "{{.GIT_REV}}"
          preview.PRNumber: "{{.GIT_PR_NUMBER}}"
          preview.commitID: "{{.GIT_REV}}"
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.GIT_REV}}"
profiles:
  - name: ci
    activation:
      - env: CI=true
    build:
      tagPolicy:
        envTemplate:
          template: "{{.GIT_REV}}"
      local:
        push: true
        concurrency: 1
        useBuildkit: true
