# Default values for todo-app
preview:
  enabled: false
  PRNumber: ""
  commitID: ""

# TODO: Replace it with the actual IP of the load balancer (run `minikube tunnel` to get the IP)
istioLoadBalancerIP: "127.0.0.1"

image:
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
